/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TracingRouteImport } from './routes/tracing'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ClusterRouteImport } from './routes/cluster'
import { Route as CacheRouteImport } from './routes/cache'
import { Route as IndexRouteImport } from './routes/index'

const TracingRoute = TracingRouteImport.update({
  id: '/tracing',
  path: '/tracing',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusterRoute = ClusterRouteImport.update({
  id: '/cluster',
  path: '/cluster',
  getParentRoute: () => rootRouteImport,
} as any)
const CacheRoute = CacheRouteImport.update({
  id: '/cache',
  path: '/cache',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cache': typeof CacheRoute
  '/cluster': typeof ClusterRoute
  '/health': typeof HealthRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/queue': typeof QueueRoute
  '/tracing': typeof TracingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cache': typeof CacheRoute
  '/cluster': typeof ClusterRoute
  '/health': typeof HealthRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/queue': typeof QueueRoute
  '/tracing': typeof TracingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cache': typeof CacheRoute
  '/cluster': typeof ClusterRoute
  '/health': typeof HealthRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/queue': typeof QueueRoute
  '/tracing': typeof TracingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cache'
    | '/cluster'
    | '/health'
    | '/logs'
    | '/metrics'
    | '/queue'
    | '/tracing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cache'
    | '/cluster'
    | '/health'
    | '/logs'
    | '/metrics'
    | '/queue'
    | '/tracing'
  id:
    | '__root__'
    | '/'
    | '/cache'
    | '/cluster'
    | '/health'
    | '/logs'
    | '/metrics'
    | '/queue'
    | '/tracing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CacheRoute: typeof CacheRoute
  ClusterRoute: typeof ClusterRoute
  HealthRoute: typeof HealthRoute
  LogsRoute: typeof LogsRoute
  MetricsRoute: typeof MetricsRoute
  QueueRoute: typeof QueueRoute
  TracingRoute: typeof TracingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracing': {
      id: '/tracing'
      path: '/tracing'
      fullPath: '/tracing'
      preLoaderRoute: typeof TracingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster': {
      id: '/cluster'
      path: '/cluster'
      fullPath: '/cluster'
      preLoaderRoute: typeof ClusterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cache': {
      id: '/cache'
      path: '/cache'
      fullPath: '/cache'
      preLoaderRoute: typeof CacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CacheRoute: CacheRoute,
  ClusterRoute: ClusterRoute,
  HealthRoute: HealthRoute,
  LogsRoute: LogsRoute,
  MetricsRoute: MetricsRoute,
  QueueRoute: QueueRoute,
  TracingRoute: TracingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
